[package]
name = "emdrive"
version = "0.1.0"
authors = ["Michael Matloka <michal@matloka.com>"]
edition = "2018"
repository = "https://github.com/Twixes/emdrive/"
license = "Apache-2.0"

[dependencies]
num = "0.4.0"
chrono = "0.4.19"
serde = "1.0.130"
tokio = { version = "1.11.0", features = ["full"] }
gotham = "0.6.0"
futures = "0.3.1"

[dev-dependencies]
pretty_assertions = "0.7"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["run-for-all", "precommit-hook", "run-cargo-test", "run-cargo-fmt"]
