[package]
name = "faksobaza"
version = "0.1.0"
authors = ["Michael Matloka <michal@matloka.com>"]
edition = "2018"
repository = "https://github.com/Twixes/faksobaza/"
license = "Apache-2.0"

[dependencies]
